# Generated by Django 3.2.9 on 2023-07-05 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.UUIDField()),
                ('item_name', models.CharField(max_length=500)),
                ('amount', models.DecimalField(decimal_places=1, default=0.0, max_digits=15)),
                ('slug', models.SlugField(blank=True, max_length=2000, null=True)),
                ('dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_category', to='store.department')),
            ],
        ),
    ]
