# Generated by Django 3.2.9 on 2023-07-05 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=500)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('item_name', models.CharField(max_length=500)),
                ('amount', models.CharField(max_length=500)),
                ('bal', models.CharField(blank=True, max_length=500, null=True)),
                ('slug', models.SlugField(blank=True, max_length=2000, null=True)),
                ('dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='micro_history_category', to='store.department')),
            ],
        ),
    ]
