# Generated by Django 3.2.9 on 2023-07-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='id',
        ),
        migrations.AlterField(
            model_name='items',
            name='item_id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
