# Generated by Django 3.2.9 on 2023-07-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20230706_0643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='items',
            name='dept',
        ),
        migrations.AddField(
            model_name='history',
            name='action',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='unit_issue',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='unit_rate',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='unit_issue',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='unit_rate',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=15),
        ),
    ]
