# Generated by Django 3.2.9 on 2023-07-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20230714_0455'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='voucher_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
