# Generated by Django 3.2.9 on 2023-07-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_history_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='dateCreated',
            field=models.DateField(auto_now=True),
        ),
    ]
